spring:
  data:
    elasticsearch:
      client:
        reactive:
          connection-timeout: 1s
          username:
          password:
          socket-timeout: 5s
          use-ssl: false
  elasticsearch:
    jest:
      connection-timeout: 3s
      multi-threaded: true
      username:
      password:
        proxy:
          host:
          port:
      read-timeout: 3s
    rest:
      connection-timeout: 1s
      username:
      password:
      read-timeout: 30s
      uris: ${ES_URIS:127.0.0.1:9200}